apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: checks.healthchecks.io
  labels:
    {{- include "hcio-check-operator.labels" . | nindent 4 }}
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: healthchecks.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string
                desc:
                  type: string
                timeout:
                  type: integer
                  default: 86400
                  minimum: 60
                  maximum: 31536000
                grace:
                  type: integer
                  default: 3600
                  minimum: 60
                  maximum: 31536000
                schedule:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                tz:
                  type: string
                  default: "UTC"
                manual_resume:
                  type: boolean
                  default: false
                methods:
                  type: string
                  default: ""
                channels:
                  type: array
                  items:
                    type: string
                unique:
                  type: array
                  items:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties: 
                uuid:
                  type: string
      additionalPrinterColumns:
      - name: UUID
        type: string
        description: This check's UUID
        jsonPath: .status.uuid
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: checks
    # singular name to be used as an alias on the CLI and for display
    singular: check
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Check
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ck